const DEFAULT_CARD_ABSOLUTE_WIDTH = 460
const DEFAULT_CARD_ABSOLUTE_HEIGHT = 215
const WIDTH_TO_HEIGHT_RATIO = DEFAULT_CARD_ABSOLUTE_HEIGHT / DEFAULT_CARD_ABSOLUTE_WIDTH

export const cardWidthToHeight = (width: number) => Math.floor(width * WIDTH_TO_HEIGHT_RATIO)
